# theme
theme: minima
title: my first blog
author: wbh81218
email: binhui.wang81218@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  my first blog to test github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
